apiVersion: v1
kind: Pod
metadata:
  name: ghost-label
  namespace: default
spec:
  containers:
  - image: ghost
    imagePullPolicy: IfNotPresent
    name: ghost
  restartPolicy: Always
  nodeSelector:
    kuber: netes
